# import IResponse from './interface.gql'
# import GenderEnum from './gender.gql'

type Query {
  login(data: LoginInput!): ResponseLoginType
}

type Mutation {
  signUp(data: SignInInput!): ResponseAuthType
}

type ResponseLoginType implements IResponse {
  statusCode: Int!
  data: UserType
  message: String
  info: String!
}

input LoginInput {
  email: String
  password: String
}

type ResponseAuthType implements IResponse {
  statusCode: Int!
  message: String
  info: String!
}

input SignInInput {
  name: String!
  lastName: String!
  email: String!
  password: String!
  gender: GenderEnum!
}

